## Numpy
- Numerical Python
- 파이썬의 고성능 과학 계산용 패키지
- 일반 List에 비해 빠르고, 메모리 효율적
- 반복문 없이 데이터 배열에 대한 처리를 지원함
- 선형대수와 관련한 다양한 기능을 제공함
- C, C++, 포트란 등의 언어와 통합 기능

In [1]:
import numpy as np

In [2]:
test_array = np.array(["1", "4", 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [6]:
type(test_array[3]) # Dynamic typing not supported(List와 차이점)

numpy.float64

In [7]:
test_array.dtype

dtype('float64')

In [8]:
test_array.shape

(4,)

### Array shape - ndim & size
- ndim - number of dimension
- size - data의 개수
```
np.array(tensor, int).ndim
np.array(tensor, int).size
```

In [10]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [11]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [14]:
test_a = np.array(test_matrix).reshape(8,)
test_a.shape

(8,)

In [15]:
test

array([1, 2, 3, 4, 1, 2, 5, 8])

In [19]:
test_b = np.array(test_matrix).flatten()
test_b

array([1, 2, 3, 4, 1, 2, 5, 8])

### Indexing & Slicing
- Indexing
```
test_example[0,0] = 12 # Matrix 0,0 에 12 할당
test_example[0][0] = 5 # Matrix 0,0 에 12 할당
# test_example[0,0] => 5
```
- Slicing
```
a = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)
a[:,2:] # 전체 Rwo의 2열 이상
a[1,1,3] # 1 Row의 1열~2열
a[1:3] # 1 Rwo ~ 2 Row의 전체
```
- List와 달리 행과 열 부분을 나눠서 slicing이 가능함
- Matrix의 부분 집합을 추출할 때 유용함

#### arange 
- array의 범위를 지정하여, 값의 list를 생성하는 명령어

In [22]:
np.arange(30) # range: List의 range와 같은 효과, integer로 0부터 29까지 배열추출

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
np.arange(0, 5, 0.5) # floating point도 표시가능함

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [24]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [25]:
np.arange(30).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

#### axis
- 모든 operation fucntion을 실행할 때, 기준이 되는 dimension 축

In [26]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

#### concatenate
- Numpy array를 합치는 함수

In [30]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [31]:
a = np.array([ [1], [2], [3]])
b = np.array([ [2], [3], [4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

#### Operations b/t arrays
- Numpy는 array간의 기본적인 사칙 연산으 지원함.

In [32]:
test_a = np.array([[1,2,3], [4,5,6]], float)

In [33]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [34]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

#### Dot product
- Matrix의 기본 연산
- dot 함수 사용

In [37]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [38]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

#### broadcasting
- Shape이 다른 배열간 연산을 지원하는 기능

In [39]:
test_matrix = np.array([[1,2,3], [4,5,6]],float)
scalar = 3 

test_matrix + scalar # Matrix - Scalar 덧셈

array([[4., 5., 6.],
       [7., 8., 9.]])

#### All & Any
- Array의 데이터 전부(and) 또는 일부(or)가 조건에 만족 여부 반환

In [40]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.any(a>5), np.any(a<0)

(True, False)

In [42]:
np.all(a>5), np.all(a<10)

(False, True)

In [43]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [44]:
a = np.array([1,3,0], float)
np.where(a>0, 3, 2)

array([3, 3, 2])

In [45]:
np.where(a>0) # index값 반환

(array([0, 1], dtype=int64),)

#### argmax & argmin
- array내 최대값 또는 최소값의 index를 반환함

In [47]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

In [48]:
# axis 기반의 반환
a = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))

#### boolean index
- numpy는 배열은 특정 조건에 따른 값을 배열 형태로 추출할 수 있음
- Comparasion operation 함수들도 모두 사용가능

In [49]:
test_array = np.array([1,4,0,2,3,8,9,7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [51]:
test_array[test_array>3] # 조건이 True인 index의 element만 추출

array([4., 8., 9., 7.])

In [53]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

#### fancy index
- numpy는 array를 index value로 사용해서 값을 추출하는 방법

In [54]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int) # 반드시 integer로 선언
a[b], a.take(b) # bracket index, b 배열의 값을 index로 하여 a의 값들을 추출함
                # take 함수 : bracket index와 같은 효과

(array([2., 2., 4., 8., 6., 4.]), array([2., 2., 4., 8., 6., 4.]))