In [1]:
import numpy as np

In [2]:
n=3
np.arange(n**2).reshape(n,n)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
def n_size_ndarray_creation(n, dtype=np.int):
    return np.array(range(n**2), dtype=dtype).reshape(n,n)

n_size_ndarray_creation(3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    if type==0:
        return np.zeros(shape=shape, dtype=dtype)
    if type==1:
        return np.ones(shape=shape, dtype=dtype)
    if type==99:
        return np.empty(shape=shape, dtype=dtype)

In [7]:
def change_shape_of_ndarray(X, n_row):
    return X.flatten() if n_row==1 else X.reshape(n_row, -1)

X = np.ones((32,32), dtype=np.int)
change_shape_of_ndarray(X, 4)

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [8]:
def concat_ndarray(X_1, X_2, axis):
    try:
        if X_1.ndim == 1:
            X_1 = X_1.reshape(1, -1)
        if X_2.ndim == 1:
            X_2 = X_2.reshape(1, -1)
        return np.concatenate((X_1, X_2), axis=axis)
    except ValueError as e:
        return False

In [9]:
def boolean_index(X, condition):
    condition = eval(str("X") + condition)
    return np.where(condition)

X = np.arange(32, dtype=np.float32)
X

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31.], dtype=float32)

In [10]:
np.where(X>6)

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 29, 30, 31], dtype=int64),)

In [11]:
boolean_index(X, "> 6")

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 29, 30, 31], dtype=int64),)

In [14]:
def find_nearest_value(X, target_value):
    return X[np.argmin(np.abs(X-target_value))]

X = np.random.uniform(0, 1, 5)
X

array([0.58695277, 0.81293487, 0.3326626 , 0.76259549, 0.38418009])

In [15]:
target_value = 0.3
find_nearest_value(X, target_value)

0.3326626016186335

In [25]:
def get_n_largest_values(X, n):
    return X[np.argsort(X)[::-1]][:n]

X = np.random.uniform(0, 1, 5)
X[np.argsort(X)[::-1]]

array([0.85641581, 0.73602852, 0.59185583, 0.33421452, 0.21658171])

In [26]:
get_n_largest_values(X, 3)

array([0.85641581, 0.73602852, 0.59185583])